SIM ?= vcs
TOP ?= randomization_tb
SRC := rand_if.sv randomization_design.sv randomization_tests.sv randomization_assertions.sv randomization_coverage.sv randomization_tb.sv
include ../../tools/Makefile
