SIM ?= vcs
TOP ?= uvm_basic_tb
SRC := uvm_basic_if.sv uvm_basic_design.sv uvm_basic_agent.sv uvm_basic_assertions.sv uvm_basic_coverage.sv uvm_basic_tests.sv uvm_basic_tb.sv
include ../../tools/Makefile
