SIM ?= vcs
TOP ?= advanced_env_tb
SRC := advanced_if.sv advanced_env_design.sv advanced_env_assertions.sv advanced_env_coverage.sv advanced_env_tests.sv advanced_env_tb.sv
include ../../tools/Makefile
