SIM ?= vcs
TOP ?= procedural_blocks_tb
SRC := proc_if.sv procedural_blocks_design.sv procedural_blocks_assertions.sv procedural_blocks_coverage.sv procedural_blocks_tests.sv procedural_blocks_tb.sv
include ../../tools/Makefile
